In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [33]:
## Define the vocabulary size
voc_size=10000

In [34]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [35]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2999, 3666, 8620, 4946],
 [2999, 3666, 8620, 9527],
 [2999, 6267, 8620, 2126],
 [4343, 1061, 2088, 3078, 5852],
 [4343, 1061, 2088, 3078, 6126],
 [3831, 2999, 3977, 8620, 599],
 [7519, 9639, 2445, 3078]]

In [36]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [37]:
import numpy as np

In [38]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2999 3666 8620 4946]
 [   0    0    0    0 2999 3666 8620 9527]
 [   0    0    0    0 2999 6267 8620 2126]
 [   0    0    0 4343 1061 2088 3078 5852]
 [   0    0    0 4343 1061 2088 3078 6126]
 [   0    0    0 3831 2999 3977 8620  599]
 [   0    0    0    0 7519 9639 2445 3078]]


In [39]:
## feature representation
dim=10

In [40]:
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile('adam','mse')

In [41]:
model.build(input_shape=(None, sent_length))
model.summary()


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [42]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step


array([[[-2.3685582e-03, -7.4369311e-03,  2.0410839e-02, -4.6364069e-02,
         -4.9969554e-02, -3.8657248e-02, -3.0608524e-02, -1.9256735e-02,
         -3.0390132e-02,  2.1708932e-02],
        [-2.3685582e-03, -7.4369311e-03,  2.0410839e-02, -4.6364069e-02,
         -4.9969554e-02, -3.8657248e-02, -3.0608524e-02, -1.9256735e-02,
         -3.0390132e-02,  2.1708932e-02],
        [-2.3685582e-03, -7.4369311e-03,  2.0410839e-02, -4.6364069e-02,
         -4.9969554e-02, -3.8657248e-02, -3.0608524e-02, -1.9256735e-02,
         -3.0390132e-02,  2.1708932e-02],
        [-2.3685582e-03, -7.4369311e-03,  2.0410839e-02, -4.6364069e-02,
         -4.9969554e-02, -3.8657248e-02, -3.0608524e-02, -1.9256735e-02,
         -3.0390132e-02,  2.1708932e-02],
        [-4.0397666e-02,  5.7504885e-03,  1.2232803e-02,  3.9800059e-02,
         -4.0005077e-02,  4.3282732e-03,  1.8161450e-02, -2.0640075e-02,
          1.3851892e-02, -3.2289922e-02],
        [-1.0524929e-02, -4.1031614e-03,  3.6767293e-02, -2.

In [47]:
embedded_docs[0]

array([   0,    0,    0,    0, 2999, 3666, 8620, 4946])

In [48]:
embedded_docs.shape

(7, 8)

In [49]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[[-0.00236856, -0.00743693,  0.02041084, -0.04636407,
         -0.04996955, -0.03865725, -0.03060852, -0.01925674,
         -0.03039013,  0.02170893],
        [-0.00236856, -0.00743693,  0.02041084, -0.04636407,
         -0.04996955, -0.03865725, -0.03060852, -0.01925674,
         -0.03039013,  0.02170893],
        [-0.00236856, -0.00743693,  0.02041084, -0.04636407,
         -0.04996955, -0.03865725, -0.03060852, -0.01925674,
         -0.03039013,  0.02170893],
        [-0.00236856, -0.00743693,  0.02041084, -0.04636407,
         -0.04996955, -0.03865725, -0.03060852, -0.01925674,
         -0.03039013,  0.02170893],
        [-0.04039767,  0.00575049,  0.0122328 ,  0.03980006,
         -0.04000508,  0.00432827,  0.01816145, -0.02064008,
          0.01385189, -0.03228992],
        [-0.01052493, -0.00410316,  0.03676729, -0.02264442,
         -0.01282675,  0.02004501, -0.00521793,  0.04467819,
          0.01484939, -0.00514019],
        [ 0.04270193, -0.04970023,  0.04913254,  0.0